# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrating',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
